[0m22:06:06.956704 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023B95A3EDC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023B986EA8E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023B986EA6A0>]}


============================== 22:06:06.966658 | 4af633bc-6650-4031-b964-5ecb546656d5 ==============================
[0m22:06:06.966658 [info ] [MainThread]: Running with dbt=1.6.6
[0m22:06:06.967774 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\lucas\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:06:06.970169 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\lucas\PycharmProjects\pythonProject\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:06:06.971201 [debug] [MainThread]: Command `dbt run` failed at 22:06:06.971201 after 0.05 seconds
[0m22:06:06.972223 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023B95A3EDC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023B986EA640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023B986EA970>]}
[0m22:06:06.973232 [debug] [MainThread]: Flushing usage events
[0m22:06:23.446192 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211964BEDC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002119916B970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002119916B730>]}


============================== 22:06:23.452708 | 73ad8d68-8c09-4f63-8514-98ab1136082b ==============================
[0m22:06:23.452708 [info ] [MainThread]: Running with dbt=1.6.6
[0m22:06:23.453706 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\lucas\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:06:36.095138 [debug] [MainThread]: Starter project path: C:\Users\lucas\PycharmProjects\pythonProject\venv\lib\site-packages\dbt\include\starter_project
[0m22:06:36.149078 [info ] [MainThread]: 
Your new dbt project "Practico3" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:06:36.150420 [info ] [MainThread]: Setting up your profile.
[0m22:06:48.295393 [debug] [MainThread]: Command `dbt init` succeeded at 22:06:48.295393 after 24.88 seconds
[0m22:06:48.297393 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211964BEDC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021193687F10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021193687700>]}
[0m22:06:48.298392 [debug] [MainThread]: Flushing usage events
[0m12:37:35.410620 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EDB223ED90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EDB4EEB760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EDB4EEB520>]}


============================== 12:37:35.423989 | 3dbf3512-b2f8-4ab3-88b3-5e8025a68081 ==============================
[0m12:37:35.423989 [info ] [MainThread]: Running with dbt=1.6.6
[0m12:37:35.426745 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\lucas\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:37:35.428267 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\lucas\PycharmProjects\pythonProject\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:37:35.430747 [debug] [MainThread]: Command `dbt run` failed at 12:37:35.430747 after 0.08 seconds
[0m12:37:35.432760 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EDB223ED90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EDB4F03AF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EDB4F039D0>]}
[0m12:37:35.433761 [debug] [MainThread]: Flushing usage events
